### ISSUE TITLE
0.12.1 release is not tagged, and editorconfig.__version__ is not updated in the repo

### ISSUE THREAD

**Issue by felixonmars** [editorconfig/editorconfig-core-py#14]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by bignose-debian** [comment]
From what I can determine, release “0.12.1” branched from commit 582fbd04.

Some changes exist in ‘master’ after that commit, and do not include the changes made for release “0.12.1”.

So, I don't know where to add a new commit that makes the changes for that release. It's not commit 582fbd04 (because that does not match the actual code as released to PyPI). It's not any of the subsequent commits on ‘master’.

There should be a new commit made which *exactly* represents the source code as released for “0.12.1”, and that's where the “0.12.1” tag (and GitHub release) should be made. But that implies re-writing public history, so it's not ideal.

**Comment by FRidh** [comment]
0.12.2 is also not tagged.

**Comment by greut** [comment]
I've created the missing tags in GitHub.
